name: Build ZMK Firmware

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout config repo
        uses: actions/checkout@v4

      - name: Install Python & west
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            git cmake ninja-build gperf python3-pip python3-dev \
            libffi-dev libssl-dev dfu-util
          pip3 install --upgrade pip
          pip3 install west

      - name: Initialize west workspace with ZMK
        run: |
          west init -m https://github.com/zmkfirmware/zmk.git zmk-workspace
          cd zmk-workspace
          west update

      - name: Build firmware (nice_nano_v2 + rhinopad shield)
        working-directory: zmk-workspace
        run: |
          west build -s zmk/app -b nice_nano_v2 -- \
            -DSHIELD=rhinopad \
            -DZMK_CONFIG=${GITHUB_WORKSPACE}/config

      - name: Upload UF2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: rhinopad-nice_nano_v2
          path: zmk-workspace/build/zephyr/zmk.uf2

